### ISSUE TITLE
brilcalc crash for 2022 with byls and xing options

### ISSUE THREAD

**Issue by clelange** [cms-bril/brilws#2]
Command:

```
lumi --normtag /cvmfs/cms-bril.cern.ch/cms-lumi-pog/Normtags/normtag_BRIL.json -i /eos/user/c/cmsdqm/www/CAF/certification/Collisions22/DCSOnly_JSONS/Cert_Collisions2022_352416_362760_eraABCDEFG_DCSOnly_TkPx.json --byls --xing
```

Output:

```
Traceback (most recent call last):
  File "/home/bril/.local/bin/brilcalc", line 8, in <module>
    sys.exit(brilcalc_main())
  File "/home/bril/.local/lib/python3.10/site-packages/brilws/cli/brilcalc_main.py", line 667, in brilcalc_main
    lumi_per_normtag(shards,qtype,dbengine,dbschema,runtot,myformatter,datasource=dsource,normtag=ntag,withBX=pargs.withBX,byls=pargs.byls,fh=fh,csvwriter=csvwriter,ptable=ptable,scalefactor=scalefactor,totz=totz,fillmin=fillmin,fillmax=fillmax,runmin=runmin,runmax=runmax,amodetagid=amodetagid,egev=egev,beamstatusid=beamstatusid,tssecmin=tssecmin,tssecmax=tssecmax,runlsSeries=rselect,hltl1map=hltl1map,ignorel1mask=parseresult['--ignore-mask'],xingMin=pargs.xingMin,xingTr=pargs.xingTr,xingId=pargs.xingId,checkjson=checkjson,datatagnameid=datatagnameid,withfileinput=withfileinput,dataset=pargs.dataset)
  File "/home/bril/.local/lib/python3.10/site-packages/brilws/cli/brilcalc_main.py", line 319, in lumi_per_normtag
    (avglumi,bxlumi) = corrector.applyCorrectionStr( normfunc,normparam, corrector.FunctionRoot(uncorrectedbxlumi,avglumi,ncollidingbx) )
  File "/home/bril/.local/lib/python3.10/site-packages/brilws/corrector.py", line 35, in applyCorrectionStr
    return applyCorrection( funcs, funcroot )
  File "/home/bril/.local/lib/python3.10/site-packages/brilws/corrector.py", line 60, in applyCorrection
    bxlumi = FunctionCaller( f, FunctionRoot(bxlumi,totlumi,fr.root[2]) )
  File "/home/bril/.local/lib/python3.10/site-packages/brilws/corrector.py", line 190, in FunctionCaller
    return myfunc(functionroot, func.fparams)
  File "/home/bril/.local/lib/python3.10/site-packages/brilws/corrector.py", line 97, in poly1d
    return P.polyval(float(ivalue),coefs)
TypeError: only length-1 arrays can be converted to Python scalars
```

I can probably also look into this, but maybe you'll be faster fixing it.

**Comment by xiezhen** [comment]
I think it's because of line 97 in corrector.py: one cannot feed an array into  the float operator. Could you try to replace float(ivalue) with np.vectorize(ivalue) or remove the float() operator around ivalue?  (I probably just added float blindly?)

**Comment by clelange** [comment]
OK, I'll try later today and will let you know/make a PR.

**Comment by clelange** [comment]
Just to report back that this command seems to take ages (more than an hour) for me to complete. Is this normal/expected?

**Comment by xiezhen** [comment]
yes, per bunch data are very large. --xing option not supposed to run with dataset larger than a fill.
ps. I'm leaving tomorrow for vacation until Dec 10, I won't reply your messages in the period.

**Comment by clelange** [comment]
When getting rid of the float conversion, it seems to be working, but e.g. on LXPLUS and the conda installation of `brilws` v3.8.1, `brilcalc` gets killed since it's taking too much memory. I see the same when running on a VM, so there seems to be some memory leak or suboptimal storing of the intermediate results. I'm running a CI job at https://gitlab.cern.ch/cms-cloud/brilws-docker/-/jobs/33657659 and that seems to be getting further, but has also been running for 1.5 hours already (and I set the timeout to 3 hrs).

Enjoy your vacations!

**Comment by xiezhen** [comment]
There is no memory leak. It's simply not possible to run large bx job . Because the large size of bx data (i.e. 3000 times of normal) are all processed in memory.

**Comment by xiezhen** [comment]
It is normal for the size of the data.

**Comment by clelange** [comment]
OK, I see. I'll make a quick PR to fix this, then you can release 3.8.2 and that's it then.
